version: '3.3'

services:
  php5apache:
    container_name: t1php5apache
    hostname: php5apache
    build: ./php5apache
    ports:
      - "41001:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: t1mysql
    hostname: mysql
    image: onejar99/mysql:5.6
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234

  phpmyadmin:
    container_name: t1phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "41002:80"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
